---
# Inventory hostnames

all:
  hosts:
    ipfs-node-1:
    ipfs-node-2:
    ipfs-node-3:
  children:
    nginx:
      hosts:
        ipfs-node-1:
    ipfs:
      hosts:
        ipfs-node-1:
        ipfs-node-2:
        ipfs-node-3:
    ipfs_cluster:
      hosts:
        ipfs-node-1:
        ipfs-node-2:
        ipfs-node-3: